apply plugin: 'com.android.library'


android {
    namespace = "com.example.util_lib"
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"

    }

}

dependencies {
    testImplementation "junit:junit:4.12"
}
