plugins {
    id 'com.android.application' version '9.0.0'
}

android {
    compileSdk 33
    defaultConfig {
        namespace "com.example.applychanges"
        targetSdk 33
        minSdk 26
    }
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_17
      targetCompatibility JavaVersion.VERSION_17
    }
    kotlin {
      compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
      }
    }
}