aswb_test_deps_repository = use_repo_rule("//tools/adt/idea/aswb/testing/test_deps:test_deps.bzl", "aswb_test_deps_repository")

aswb_test_deps_repository(
    name = "aswb_test_deps",
    artifacts = {
        "https://dl.google.com/go/go1.22.4.linux-amd64.tar.gz": "ba79d4526102575196273416239cca418a651e049c2b099f3159db85e7bade7d",
        "https://github.com/JetBrains/kotlin/releases/download/v2.1.0/kotlin-compiler-2.1.0.zip": "b6698d5728ad8f9edcdd01617d638073191d8a03139cc538a391b4e3759ad297",
        "https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz": "9b7a064305e9fd94d124ffa6cc358592eb42b5da588fb4e07d09254aa40086db",
        "https://github.com/abseil/abseil-py/archive/refs/tags/v2.1.0.tar.gz": "8a3d0830e4eb4f66c4fa907c06edf6ce1c719ced811a12e26d9d3162f8471758",
        "https://github.com/bazel-contrib/bazel-gazelle/releases/download/v0.40.0/bazel-gazelle-v0.40.0.tar.gz": "a80893292ae1d78eaeedd50d1cab98f242a17e3d5741b1b9fb58b5fd9d2d57bc",
        "https://github.com/bazel-contrib/bazel_features/releases/download/v1.33.0/bazel_features-v1.33.0.tar.gz": "c41853e3b636c533b86bf5ab4658064e6cc9db0a3bce52cbff0629e094344ca9",
        "https://github.com/bazel-contrib/rules_go/releases/download/v0.51.0-rc2/rules_go-v0.51.0-rc2.zip": "1101d7e81a6e7f9cee94dd947bed705144bf339257fbec1d73d620df87e58885",
        "https://github.com/bazelbuild/apple_support/releases/download/1.20.0/apple_support.1.20.0.tar.gz": "1bb8059831503602c2eb4d3d0a61c3e75ba4a2bbd43c1603cb79fe9bdcfdde51",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.1/bazel-skylib-1.8.1.tar.gz": "51b5105a760b353773f904d2bbc5e664d0987fbaf22265164de65d43e910d8ac",
        "https://github.com/bazelbuild/bazel-worker-api/releases/download/v0.0.4/bazel-worker-api-v0.0.4.tar.gz": "79b30bcdab8cb0dce1523b28ff798067419715f5540a8a446bbccf393e5eb79c",
        "https://github.com/bazelbuild/platforms/releases/download/0.0.11/platforms-0.0.11.tar.gz": "29742e87275809b5e598dc2f04d86960cc7a55b3067d97221c9abbc9926bff0f",
        "https://github.com/bazelbuild/rules_android/releases/download/v0.6.4/rules_android-v0.6.4.tar.gz": "4135e2fa37a94bb36c7801e33faef2934c9fe4f9a84d0035eacc4154c2c30e44",
        "https://github.com/bazelbuild/rules_android_ndk/releases/download/v0.1.3/rules_android_ndk-v0.1.3.tar.gz": "89bf5012567a5bade4c78eac5ac56c336695c3bfd281a9b0894ff6605328d2d5",
        "https://github.com/bazelbuild/rules_cc/releases/download/0.1.1/rules_cc-0.1.1.tar.gz": "712d77868b3152dd618c4d64faaddefcc5965f90f5de6e6dd1d5ddcd0be82d42",
        "https://github.com/bazelbuild/rules_java/releases/download/8.11.0/rules_java-8.11.0.tar.gz": "d31b6c69e479ffa45460b64dc9c7792a431cac721ef8d5219fc9f603fa2ff877",
        "https://github.com/bazelbuild/rules_jvm_external/releases/download/6.7/rules_jvm_external-6.7.tar.gz": "a1e351607f04fed296ba33c4977d3fe2a615ed50df7896676b67aac993c53c18",
        "https://github.com/bazelbuild/rules_kotlin/releases/download/v2.1.3/rules_kotlin-v2.1.3.tar.gz": "e1448a56b2462407b2688dea86df5c375b36a0991bd478c2ddd94c97168125e2",
        "https://github.com/bazelbuild/rules_license/releases/download/1.0.0/rules_license-1.0.0.tar.gz": "26d4021f6898e23b82ef953078389dd49ac2b5618ac564ade4ef87cced147b38",
        "https://github.com/bazelbuild/rules_pkg/releases/download/1.1.0/rules_pkg-1.1.0.tar.gz": "b7215c636f22c1849f1c3142c72f4b954bb12bb8dcf3cbe229ae6e69cc6479db",
        "https://github.com/bazelbuild/rules_proto/releases/download/7.1.0/rules_proto-7.1.0.tar.gz": "14a225870ab4e91869652cfd69ef2028277fc1dc4910d65d353b62d6e0ae21f4",
        "https://github.com/bazel-contrib/rules_python/releases/download/1.6.0/rules_python-1.6.0.tar.gz": "fa7dd2c6b7d63b3585028dd8a90a6cf9db83c33b250959c2ee7b583a6c130e12",
        "https://github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz": "d8cd4a3a91fc1dc68d4c7d6b655f09def109f7186437e3f50a9b60ab436a0c53",
        "https://github.com/bazelbuild/rules_testing/releases/download/v0.8.0/rules_testing-v0.8.0.tar.gz": "89feaf18d6e2fc07ed7e34510058fc8d48e45e6d2ff8a817a718e8c8e4bcda0e",
        "https://github.com/bazelbuild/stardoc/releases/download/0.7.2/stardoc-0.7.2.tar.gz": "0e1ed4a98f26e718776bd64d053d02bb34d98572ccd03d6ba355112a1205706b",
        "https://github.com/google/ksp/releases/download/1.9.23-1.0.20/artifacts.zip": "ee0618755913ef7fd6511288a232e8fad24838b9af6ea73972a76e81053c8c2d",
        "https://github.com/google/ksp/releases/download/2.1.0-1.0.28/artifacts.zip": "fc27b08cadc061a4a989af01cbeccb613feef1995f4aad68f2be0f886a3ee251",
        "https://github.com/astral-sh/python-build-standalone/releases/download/20250808/cpython-3.11.13+20250808-x86_64-unknown-linux-gnu-install_only.tar.gz": "3ad988c702cbb017fef1208d47dea4138a2e85fd0f7f01ec5e1e335e597131b9",
        "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz": "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23",
        "https://github.com/protocolbuffers/protobuf/releases/download/v33.2/protobuf-33.2.tar.gz": "6b6599b54c88d75904b7471f5ca34a725fa0af92e134dd1a32d5b395aa4b4ca8",
        "https://mirror.bazel.build/android.googlesource.com/platform/dalvik/+archive/5a81c499a569731e2395f7c8d13c0e0d4e17a2b6.tar.gz": "86b4848c038bf687fadc812239cb01fb8d1d15cef3125b480a0448360992b95d",
        "https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.31.0.tar": "d7cdfc03f3ad6571b7719f4355379177a4bde68d17dca2bdbf6c274d72e4d6cf",
        "https://mirror.bazel.build/bazel_java_tools/releases/java/v13.18/java_tools-v13.18.zip": "1945286e31ca21184b672290caa83cc3470dcdbd00ce0af34f02d24398974ebf",
        "https://mirror.bazel.build/bazel_java_tools/releases/java/v13.18/java_tools_linux-v13.18.zip": "0da77fca085dd477a057581f26fe677d88e4b9f542c517d813e50553829f66a0",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.50.19-ca-jdk17.0.11-linux_x64.tar.gz": "a1e8ac9ae5804b84dc07cf9d8ebe1b18247d70c92c1e0de97ea10109563f4379",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu21.36.17-ca-jdk21.0.4-linux_x64.tar.gz": "318d0c2ed3c876fb7ea2c952945cdcf7decfb5264ca51aece159e635ac53d544",
        "https://mirror.bazel.build/coursier_cli/coursier_cli_v2_1_24.jar": "8c724dc204534353ea8263ba0af624979658f7ab62395f35b04f03ce5714f330",
        "https://mirror.bazel.build/github.com/bazel-contrib/rules_go/releases/download/v0.53.0/rules_go-v0.53.0.zip": "b78f77458e77162f45b4564d6b20b6f92f56431ed59eaaab09e7819d1d850313",
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.40.0/rules_go-v0.40.0.zip": "bfc5ce70b9d1634ae54f4e7b495657a18a04e0d596785f672d35d5f505ab491a",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-core-jvm/1.6.3/kotlinx-serialization-core-jvm-1.6.3.jar": "29c821a8d4e25cbfe4f2ce96cdd4526f61f8f4e69a135f9612a34a81d93b65f1",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json-jvm/1.6.3/kotlinx-serialization-json-jvm-1.6.3.jar": "d3234179bcff1886d53d67c11eca47f7f3cf7b63c349d16965f6db51b7f3dd9a",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json/1.6.3/kotlinx-serialization-json-1.6.3.jar": "8c0016890a79ab5980dd520a5ab1a6738023c29aa3b6437c482e0e5fdc06dab1",
        # Gazelle dependencies.
        "https://github.com/golang/sync/archive/refs/tags/v0.8.0.tar.gz": "1872b89e8bf234d4c65edca0bf7c7fd6c414cf74a5a9e10463eb2483cf7b361f",
        "https://github.com/golang/protobuf/archive/refs/tags/v1.5.4.tar.gz": "d75e6960ecfabaaa83a7261b1b630d24e9c63aca79615fb15bf33e11b62fd019",
        "https://github.com/protocolbuffers/protobuf-go/archive/refs/tags/v1.36.3.tar.gz": "d15b5c42786fa47d716b1572e5ba21979dc3163121854ece5101f072d4fa95bb",
        "https://bitbucket.org/creachadair/stringset/get/344423ca24817f0ff8371b5b6ad96f9848a5c109.tar.gz": "c53d3526e766cd95c24e6e59c2e3f141c2001382f2eaab338a50e8cf8f8aa76c",
        "https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.8.zip": "172be177db06b16632335f27d50cee0786fb1873df344852db71b2171cd6d996",
        # Bazel 9 module dependencies.
        "https://github.com/abseil/abseil-cpp/releases/download/20250814.1/abseil-cpp-20250814.1.tar.gz": "1692f77d1739bacf3f94337188b78583cf09bab7e420d2dc6c5605a4f86785a1",
        "https://github.com/apple/swift-argument-parser/archive/refs/tags/1.3.1.tar.gz": "4d964f874b251abc280ee28f0f187de3c13a6122a9561524f66a10768ca2d837",
        "https://github.com/bazel-contrib/bazel-gazelle/releases/download/v0.47.0/bazel-gazelle-v0.47.0.tar.gz": "675114d8b433d0a9f54d81171833be96ebc4113115664b791e6f204d58e93446",
        "https://github.com/bazel-contrib/bazel_features/releases/download/v1.42.1/bazel_features-v1.42.1.tar.gz": "8189bac9a6bf9cc155a854c4cbebfebf58b9ca7a2d0a67645f7d0c1f83c523ac",
        "https://github.com/bazel-contrib/rules_go/releases/download/v0.59.0/rules_go-v0.59.0.zip": "68af54cb97fbdee5e5e8fe8d210d15a518f9d62abfd71620c3eaff3b26a5ff86",
        "https://github.com/bazel-contrib/rules_jvm_external/releases/download/6.9/rules_jvm_external-6.9.tar.gz": "3c41eae4226a7dfdce7b213bc541557b8475c92da71e2233ec7c306630243a65",
        "https://github.com/bazel-contrib/rules_python/releases/download/1.7.0/rules_python-1.7.0.tar.gz": "f609f341d6e9090b981b3f45324d05a819fd7a5a56434f849c761971ce2c47da",
        "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.5/supply-chain-v0.0.5.tar.gz": "49ed11e5d6b752c55fa539cbb10b2736974f347b081d7bd500a80dacb7dbec06",
        "https://github.com/bazelbuild/apple_support/releases/download/1.24.2/apple_support.1.24.2.tar.gz": "8625cc7b7b2952e38101e17b4a9e7c043b3a79f55d26e4772819891998725e16",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz": "6e78f0e57de26801f6f564fa7c4a48dc8b36873e416257a92bbb0937eeac8446",
        "https://github.com/bazelbuild/bazel-worker-api/releases/download/v0.0.11/bazel-worker-api-v0.0.11.tar.gz": "be4fab72014dc0bd92ead5146fe9ae9939bdcd262453699bb52b61e42f864e85",
        "https://github.com/bazelbuild/platforms/releases/download/1.0.0/platforms-1.0.0.tar.gz": "3384eb1c30762704fbe38e440204e114154086c8fc8a8c2e3e28441028c019a8",
        "https://github.com/bazelbuild/rules_android/releases/download/v0.7.3/rules_android-v0.7.3.tar.gz": "c4cd258d3761eff08ee044c0252179bb6ee8af8ab24f7dafb73b280eeda98243",
        "https://github.com/bazelbuild/rules_android_ndk/releases/download/v0.1.5/rules_android_ndk-v0.1.5.tar.gz": "07e7a2777113bb3d0a432265d1c78cfaa140a5bc4c82be4c8cd988b34382ec90",
        "https://github.com/bazelbuild/rules_apple/releases/download/4.1.0/rules_apple.4.1.0.tar.gz": "20152b14d9a420afc15ace905c02fd6425ddceb084630f3f043b287adf0fcdbd",
        "https://github.com/bazelbuild/rules_cc/releases/download/0.2.17/rules_cc-0.2.17.tar.gz": "283fa1cdaaf172337898749cf4b9b1ef5ea269da59540954e51fba0e7b8f277a",
        "https://github.com/bazelbuild/rules_java/releases/download/9.3.0/rules_java-9.3.0.tar.gz": "6ef26d4f978e8b4cf5ce1d47532d70cb62cd18431227a1c8007c8f7843243c06",
        "https://github.com/bazelbuild/rules_pkg/releases/download/1.2.0/rules_pkg-1.2.0.tar.gz": "b5c9184a23bb0bcff241981fd9d9e2a97638a1374c9953bb1808836ce711f990",
        "https://github.com/bazelbuild/rules_shell/releases/download/v0.6.1/rules_shell-v0.6.1.tar.gz": "e6b87c89bd0b27039e3af2c5da01147452f240f75d505f5b6880874f31036307",
        "https://github.com/bazelbuild/rules_swift/releases/download/3.1.2/rules_swift.3.1.2.tar.gz": "5eff717c18bb513285b499add68f2331509cd4e411ff085e96a86b3342c1e5aa",
        "https://github.com/google/googletest/releases/download/v1.17.0/googletest-1.17.0.tar.gz": "65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c",
        "https://github.com/google/re2/releases/download/2024-07-02/re2-2024-07-02.zip": "a835fe55fbdcd8e80f38584ab22d0840662c67f2feb36bd679402da9641dc71e",
        "https://github.com/nlohmann/json/releases/download/v3.6.1/include.zip": "69cc88207ce91347ea530b227ff0776db82dcb8de6704e1a3d74f4841bc651cf",
        "https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.6.tar.gz": "f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2",
        "https://github.com/protocolbuffers/protobuf/releases/download/v33.4/protobuf-33.4.bazel.tar.gz": "687e98a471973b5c5fd711750c40b8b82c0ade33f649db65e00b290f29345a2b",
        "https://github.com/pybind/pybind11_bazel/releases/download/v2.12.0/pybind11_bazel-2.12.0.zip": "a58c25c5fe063a70057fa20cb8e15f3bda19b1030305bcb533af1e45f36a4a55",
        "https://github.com/robolectric/robolectric-bazel/releases/download/4.14.1.2/robolectric-bazel-4.14.1.2.tar.gz": "b2d2164bae80fcfbdd078eb2f0935ba06557402b8c814928d9e3bec7358e2b7b",
        # Bazel 9 toolchains.
        "https://mirror.bazel.build/bazel_java_tools/releases/java/v18.1/java_tools-v18.1.zip": "27cab59ba5ff8ee7cf3071971fe2587a295daefe82531f27b4f061111276163d",
        "https://mirror.bazel.build/bazel_java_tools/releases/java/v18.1/java_tools_linux-v18.1.zip": "e22cbb2600249576c6a0a02af3f78e26537a89b6be11ef3826c01f9019faaa61",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.62.17-ca-jdk17.0.17-linux_x64.tar.gz": "1dcbbed73e95dc35f5c60402a84936f6830ff43c2a0dc0037a5657dbc25472c1",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu21.46.19-ca-jdk21.0.9-linux_x64.tar.gz": "67e810b31427ac0ff1c249473595066a00bdf0f9265df186c32905d5f75c93b8",
        "https://github.com/bazelbuild/rules_kotlin/releases/download/v2.2.2/rules_kotlin-v2.2.2.tar.gz": "411db26afb3492cc8351b5b5349931522afe2c54f2651b6d127730a1256d0f60",
        "https://github.com/fmeum/buildozer/releases/download/v8.5.1/buildozer-v8.5.1.tar.gz": "bd0786e0f8b6aed8c35898b4c06f64ba853d61d7c8361edb5a8d43c6ea37f5c6",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.84.17-ca-jdk11.0.29-linux_x64.tar.gz": "681b2e4bf7fedf4d20666fc2a954b83ff5675ccfb916c867267d29c85c2ee310",
        "https://github.com/astral-sh/python-build-standalone/releases/download/20251014/cpython-3.11.14+20251014-x86_64-unknown-linux-gnu-install_only.tar.gz": "d0623c777fb89b904b56cd5aba51af29cbb34b1f9d45f0672f90f6dce30fa93e",
        "https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu25.30.17-ca-jdk25.0.1-linux_x64.tar.gz": "471b3e62bdffaed27e37005d842d8639f10d244ccce1c7cdebf7abce06c8313e",
        "https://github.com/JetBrains/kotlin/releases/download/v2.2.21/kotlin-compiler-2.2.21.zip": "a623871f1cd9c938946948b70ef9170879f0758043885bbd30c32f024e511714",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-build-tools-impl/2.2.21/kotlin-build-tools-impl-2.2.21.jar": "458b63ef8fc50a0a3180fe688ec1b995745992a05c495dac61e58d1088927a80",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-core-jvm/1.8.1/kotlinx-serialization-core-jvm-1.8.1.jar": "3565b6d4d789bf70683c45566944287fc1d8dc75c23d98bd87d01059cc76f2b3",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json/1.8.1/kotlinx-serialization-json-1.8.1.jar": "58adf3358a0f99dd8d66a550fbe19064d395e0d5f7f1e46515cd3470a56fbbb0",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json-jvm/1.8.1/kotlinx-serialization-json-jvm-1.8.1.jar": "8769e5647557e3700919c32d508f5c5dad53c5d8234cd10846354fbcff14aa24",
        "https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.9.zip": "aab349130118497d86bc79e3f735f026d3c36e7d38529063e91da1c29cc2ea47",
        "https://github.com/google/ksp/releases/download/2.3.3/artifacts.zip": "24cb0d869ab2ae9fcf630a747b6b7e662e4be26e8b83b9272f6f3c24813e0c5a",
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.10.2/kotlinx-coroutines-core-jvm-1.10.2.jar": "5ca175b38df331fd64155b35cd8cae1251fa9ee369709b36d42e0a288ccce3fd",
    },
    bazel8_sha256 = "7ff2b6a675b59a791d007c526977d5262ade8fa52efc8e0d1ff9e18859909fc0",
    bazel8_url = "https://github.com/bazelbuild/bazel/releases/download/8.2.1/bazel-8.2.1-linux-x86_64",
    bazel9_sha256 = "7668a95db1250f12c40407251e4e203b4ec8bf39bc495d2f485b2d8c99048694",
    bazel9_url = "https://github.com/bazelbuild/bazel/releases/download/9.2.0/bazel-9.2.0-linux-x86_64",
    bcr_sha256 = "00d9893b73641b17f1a11abf6410652c01bc7935bd64c90b5abe6fac92a5d305",
    bcr_url = "https://github.com/bazelbuild/bazel-central-registry/archive/96f0b6d6700fd2722770e47f09e78b3003fd1c65.zip",
    projects = "tools/adt/idea/aswb/testing/test_deps/projects",
)
