# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.concurrency",
    srcs = ["src"],
    iml_files = ["intellij.android.concurrency.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "@intellij//:intellij-sdk",
        "//tools/base/common:studio.android.sdktools.common",
    ],
)

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.concurrency.tests",
    iml_files = ["intellij.android.concurrency.tests.iml"],
    test_class = "com.android.tools.idea.concurrency.AndroidConcurrencyTestSuite",
    # do not sort: must match IML order
    test_deps = [
        "//tools/adt/idea/android-concurrency:intellij.android.concurrency",
        "//tools/adt/idea/.idea/libraries:junit4",
        "//tools/adt/idea/.idea/libraries:truth",
        "//tools/adt/idea/.idea/libraries:jetbrains.kotlinx.coroutines.test",
        "//tools/base/testutils:studio.android.sdktools.testutils",
        "@intellij//:test-framework",
        "//tools/adt/idea/adt-testutils:intellij.android.adt.testutils",
    ],
    test_srcs = ["test"],
    visibility = ["//visibility:public"],
    deps = ["@intellij//:intellij-sdk"],
)
