plugins {
    id 'com.android.library'
}

android {
    namespace = 'com.google.mylibrary'
    compileSdk 33

    defaultConfig {
        minSdk 24
        targetSdk 33
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

  kotlin {
    compilerOptions {
      jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
  }
}

dependencies {
}