/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.npw.model

import com.android.annotations.concurrency.WorkerThread
import com.android.tools.idea.templates.recipe.RenderingContext
import com.android.tools.idea.wizard.template.RecipeExecutor
import com.android.tools.idea.wizard.template.Template
import com.intellij.openapi.extensions.ExtensionPointName
import com.intellij.openapi.project.Project
import com.intellij.ui.components.JBLabel
import java.io.File
import javax.swing.JComponent

/**
 * The New Project Template machinery is deeply tied to Gradle. This strategy gives us hooks to customize it for alternate template
 * rendering strategies, even though it also intercepts project creation and sync.
 */
interface TemplateRendererStrategy<AdditionalUserSettingsT : TemplateRendererStrategy.AdditionalUserSettings> {
  val id: String
  val displayName: String

  fun createRecipeExecutor(context: RenderingContext, additionalUserSettings: AdditionalUserSettingsT): RecipeExecutor

  fun createProject(projectName: String, projectBaseDirectory: File): Project

  fun initializeProject(project: Project)

  fun syncProject(project: Project)

  fun isProjectApplicable(project: Project): Boolean

  /** Returns true if this project system supports the specific template. Default to true to maintain backward compatibility. */
  fun isTemplateApplicable(template: Template): Boolean = true

  /**
   * Returns true if standard Android module files (manifest, res, icons, directory structure) should be generated by the template recipes.
   */
  val generateStandardAndroidModuleFiles: Boolean
    get() = true

  /** Returns true if files should be opened immediately in the editor before indexing completes. */
  fun isOpenImmediate(): Boolean = false

  /** Stateful additional settings that will be shown in the configure android project step when this render strategy is used. */
  interface AdditionalUserSettings {

    /** Components to render to allow the user to customize the settings */
    val labeledComponents: List<Pair<JBLabel, JComponent>>

    /** Background work to initialize the user settings, such as by fetching available versions. */
    @WorkerThread fun backgroundInitialize()
  }

  /**
   * Instantiates the (stateful) additional settings holder for this custom template.
   *
   * This will always be called, even if the renderer strategy isn't selected by the user, so all computation should be deferred to
   * backgroundInitialize.
   */
  fun createAdditionalUserSettings(): AdditionalUserSettingsT

  companion object {
    @JvmField val EP_NAME = ExtensionPointName.create<TemplateRendererStrategy<*>>("com.android.tools.idea.npw.templateRenderer")

    @JvmStatic
    fun getTemplateRendererStrategy(project: Project): TemplateRendererStrategy<*>? {
      return EP_NAME.extensions.firstOrNull { it.isProjectApplicable(project) }
    }
  }
}
