syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "metrics.proto";

option java_multiple_files = true;
option java_outer_classname = "AnomaliesServiceProto";
option java_package = "com.google.play.developer.reporting";

service AnomaliesService {
  rpc ListAnomalies(ListAnomaliesRequest) returns (ListAnomaliesResponse) {}
}
message Anomaly {
  string name = 1;
  string metric_set = 2;
  TimelineSpec timeline_spec = 3;
  repeated DimensionValue dimensions = 4;
  MetricValue metric = 5;
}
message ListAnomaliesRequest {
  string parent = 1;
  string filter = 2;
  int32 page_size = 3;
  string page_token = 4;
}
message ListAnomaliesResponse {
  repeated Anomaly anomalies = 1;
  string next_page_token = 2;
}
