syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "metrics.proto";

option java_multiple_files = true;
option java_outer_classname = "InstallBaseServiceProto";
option java_package = "com.google.play.developer.reporting";

service InstallBaseService {
  rpc GetInstallBaseMetricSet(GetInstallBaseMetricSetRequest)
      returns (InstallBaseMetricSet) {}
  rpc QueryInstallBaseMetricSet(QueryInstallBaseMetricSetRequest)
      returns (QueryInstallBaseMetricSetResponse) {}
}
message InstallBaseMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message GetInstallBaseMetricSetRequest {
  string name = 1;
}
message QueryInstallBaseMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
}
message QueryInstallBaseMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
