syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "google/type/datetime.proto";
import "google/type/decimal.proto";

option java_multiple_files = true;
option java_outer_classname = "MetricsProto";
option java_package = "com.google.play.developer.reporting";

message FreshnessInfo {
  message Freshness {
    AggregationPeriod aggregation_period = 1;
    type.DateTime latest_end_time = 2;
  }
  repeated Freshness freshnesses = 1;
}
message TimelineSpec {
  AggregationPeriod aggregation_period = 1;
  type.DateTime start_time = 2;
  type.DateTime end_time = 3;
}
message DimensionValue {
  string dimension = 1;
  oneof value {
    string string_value = 2;
    int64 int64_value = 3;
  }
  string value_label = 4;
}
message MetricValue {
  string metric = 1;
  oneof value {
    type.Decimal decimal_value = 2;
  }
  oneof confidence_interval {
    DecimalConfidenceInterval decimal_value_confidence_interval = 3;
  }
}
message DecimalConfidenceInterval {
  type.Decimal lower_bound = 1;
  type.Decimal upper_bound = 2;
}
message MetricsRow {
  AggregationPeriod aggregation_period = 1;
  type.DateTime start_time = 2;
  repeated DimensionValue dimensions = 3;
  repeated MetricValue metrics = 4;
}
enum AggregationPeriod {
  AGGREGATION_PERIOD_UNSPECIFIED = 0;
  HOURLY = 1;
  DAILY = 2;
  FULL_RANGE = 3;
}
enum UserCohort {
  USER_COHORT_UNSPECIFIED = 0;
  OS_PUBLIC = 1;
  OS_BETA = 2;
  APP_TESTERS = 3;
}
