syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "acquisitions.proto";
import "engagement.proto";
import "first_opens.proto";
import "impressions.proto";
import "ratings.proto";
import "releases.proto";
import "retention.proto";
import "store_listings.proto";

option java_multiple_files = true;
option java_outer_classname = "ReportingServiceProto";
option java_package = "com.google.play.developer.reporting";

service ReportingService {
  rpc FetchReleaseFilterOptions(FetchReleaseFilterOptionsRequest)
      returns (ReleaseFilterOptions) {}
  rpc SearchAccessibleApps(SearchAccessibleAppsRequest)
      returns (SearchAccessibleAppsResponse) {}
  rpc GetFirstOpensMetricSet(GetFirstOpensMetricSetRequest)
      returns (FirstOpensMetricSet) {}
  rpc QueryFirstOpensMetricSet(QueryFirstOpensMetricSetRequest)
      returns (QueryFirstOpensMetricSetResponse) {}
  rpc GetAverageRatingsMetricSet(GetAverageRatingsMetricSetRequest)
      returns (AverageRatingsMetricSet) {}
  rpc QueryAverageRatingsMetricSet(QueryAverageRatingsMetricSetRequest)
      returns (QueryAverageRatingsMetricSetResponse) {}
  rpc GetGooglePlayRatingMetricSet(GetGooglePlayRatingMetricSetRequest)
      returns (GooglePlayRatingMetricSet) {}
  rpc QueryGooglePlayRatingMetricSet(QueryGooglePlayRatingMetricSetRequest)
      returns (QueryGooglePlayRatingMetricSetResponse) {}
  rpc GetEngagementMetricSet(GetEngagementMetricSetRequest)
      returns (EngagementMetricSet) {}
  rpc QueryEngagementMetricSet(QueryEngagementMetricSetRequest)
      returns (QueryEngagementMetricSetResponse) {}
  rpc GetAcquisitionsMetricSet(GetAcquisitionsMetricSetRequest)
      returns (AcquisitionsMetricSet) {}
  rpc QueryAcquisitionsMetricSet(QueryAcquisitionsMetricSetRequest)
      returns (QueryAcquisitionsMetricSetResponse) {}
  rpc GetImpressionsMetricSet(GetImpressionsMetricSetRequest)
      returns (ImpressionsMetricSet) {}
  rpc QueryImpressionsMetricSet(QueryImpressionsMetricSetRequest)
      returns (QueryImpressionsMetricSetResponse) {}
  rpc GetRetentionMetricSet(GetRetentionMetricSetRequest)
      returns (RetentionMetricSet) {}
  rpc QueryRetentionMetricSet(QueryRetentionMetricSetRequest)
      returns (QueryRetentionMetricSetResponse) {}
  rpc GetStoreListingMetricSet(GetStoreListingMetricSetRequest)
      returns (StoreListingMetricSet) {}
  rpc QueryStoreListingMetricSet(QueryStoreListingMetricSetRequest)
      returns (QueryStoreListingMetricSetResponse) {}
}
message FetchReleaseFilterOptionsRequest {
  string name = 1;
}
message ReleaseFilterOptions {
  repeated Track tracks = 1;
}
message SearchAccessibleAppsRequest {
  int32 page_size = 1;
  string page_token = 2;
}
message SearchAccessibleAppsResponse {
  repeated App apps = 1;
  string next_page_token = 2;
}
message App {
  string name = 1;
  string package_name = 2;
  string display_name = 3;
}
