syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "metrics.proto";

option java_multiple_files = true;
option java_outer_classname = "VitalsServiceProto";
option java_package = "com.google.play.developer.reporting";

service VitalsService {
  rpc GetCrashRateMetricSet(GetCrashRateMetricSetRequest)
      returns (CrashRateMetricSet) {}
  rpc QueryCrashRateMetricSet(QueryCrashRateMetricSetRequest)
      returns (QueryCrashRateMetricSetResponse) {}
  rpc GetAnrRateMetricSet(GetAnrRateMetricSetRequest)
      returns (AnrRateMetricSet) {}
  rpc QueryAnrRateMetricSet(QueryAnrRateMetricSetRequest)
      returns (QueryAnrRateMetricSetResponse) {}
  rpc GetLmkRateMetricSet(GetLmkRateMetricSetRequest)
      returns (LmkRateMetricSet) {}
  rpc QueryLmkRateMetricSet(QueryLmkRateMetricSetRequest)
      returns (QueryLmkRateMetricSetResponse) {}
  rpc GetExcessiveWakeupRateMetricSet(GetExcessiveWakeupRateMetricSetRequest)
      returns (ExcessiveWakeupRateMetricSet) {}
  rpc QueryExcessiveWakeupRateMetricSet(
      QueryExcessiveWakeupRateMetricSetRequest)
      returns (QueryExcessiveWakeupRateMetricSetResponse) {}
  rpc GetStuckBackgroundWakelockRateMetricSet(
      GetStuckBackgroundWakelockRateMetricSetRequest)
      returns (StuckBackgroundWakelockRateMetricSet) {}
  rpc QueryStuckBackgroundWakelockRateMetricSet(
      QueryStuckBackgroundWakelockRateMetricSetRequest)
      returns (QueryStuckBackgroundWakelockRateMetricSetResponse) {}
  rpc GetSlowStartRateMetricSet(GetSlowStartRateMetricSetRequest)
      returns (SlowStartRateMetricSet) {}
  rpc QuerySlowStartRateMetricSet(QuerySlowStartRateMetricSetRequest)
      returns (QuerySlowStartRateMetricSetResponse) {}
  rpc GetSlowRenderingRateMetricSet(GetSlowRenderingRateMetricSetRequest)
      returns (SlowRenderingRateMetricSet) {}
  rpc QuerySlowRenderingRateMetricSet(QuerySlowRenderingRateMetricSetRequest)
      returns (QuerySlowRenderingRateMetricSetResponse) {}
}
message GetCrashRateMetricSetRequest {
  string name = 1;
}
message CrashRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryCrashRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QueryCrashRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetAnrRateMetricSetRequest {
  string name = 1;
}
message AnrRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryAnrRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QueryAnrRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetLmkRateMetricSetRequest {
  string name = 1;
}
message LmkRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryLmkRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QueryLmkRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetExcessiveWakeupRateMetricSetRequest {
  string name = 1;
}
message ExcessiveWakeupRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryExcessiveWakeupRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QueryExcessiveWakeupRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetStuckBackgroundWakelockRateMetricSetRequest {
  string name = 1;
}
message StuckBackgroundWakelockRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryStuckBackgroundWakelockRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QueryStuckBackgroundWakelockRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetSlowStartRateMetricSetRequest {
  string name = 1;
}
message SlowStartRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QuerySlowStartRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QuerySlowStartRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message GetSlowRenderingRateMetricSetRequest {
  string name = 1;
}
message SlowRenderingRateMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QuerySlowRenderingRateMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  string filter = 7;
  int32 page_size = 5;
  string page_token = 6;
  UserCohort user_cohort = 8;
}
message QuerySlowRenderingRateMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
