syntax = "proto3";

package google.play.developer.reporting.v1beta1;

import "common.proto";
import "device.proto";
import "google/protobuf/timestamp.proto";
import "google/type/decimal.proto";
import "metrics.proto";

option java_multiple_files = true;
option java_outer_classname = "VitalsErrorsServiceProto";
option java_package = "com.google.play.developer.reporting";

service VitalsErrorsService {
  rpc SearchErrorReports(SearchErrorReportsRequest)
      returns (SearchErrorReportsResponse) {}
  rpc SearchErrorIssues(SearchErrorIssuesRequest)
      returns (SearchErrorIssuesResponse) {}
  rpc GetErrorCountMetricSet(GetErrorCountMetricSetRequest)
      returns (ErrorCountMetricSet) {}
  rpc QueryErrorCountMetricSet(QueryErrorCountMetricSetRequest)
      returns (QueryErrorCountMetricSetResponse) {}
}
message ErrorReport {
  string name = 1;
  ErrorType type = 2;
  string report_text = 3;
  string issue = 4;
  google.protobuf.Timestamp event_time = 5;
  DeviceModelSummary device_model = 6;
  OsVersion os_version = 7;
  AppVersion app_version = 8;
  string vcs_information = 9;
}
message ErrorIssue {
  string name = 1;
  ErrorType type = 2;
  string cause = 3;
  string location = 4;
  int64 error_report_count = 5;
  int64 distinct_users = 6;
  google.type.Decimal distinct_users_percent = 14;
  google.protobuf.Timestamp last_error_report_time = 7;
  string issue_uri = 8;
  OsVersion first_os_version = 9;
  OsVersion last_os_version = 10;
  AppVersion first_app_version = 11;
  AppVersion last_app_version = 12;
  repeated IssueAnnotation annotations = 13;
  repeated string sample_error_reports = 15;
}
message SearchErrorReportsRequest {
  string parent = 1;
  DateTimeInterval interval = 2;
  int32 page_size = 3;
  string page_token = 4;
  string filter = 5;
}
message SearchErrorReportsResponse {
  repeated ErrorReport error_reports = 1;
  string next_page_token = 2;
}
message SearchErrorIssuesRequest {
  string parent = 1;
  DateTimeInterval interval = 2;
  int32 page_size = 3;
  string page_token = 4;
  string filter = 5;
  string order_by = 6;
  int32 sample_error_report_limit = 7;
}
message SearchErrorIssuesResponse {
  repeated ErrorIssue error_issues = 1;
  string next_page_token = 2;
}
message GetErrorCountMetricSetRequest {
  string name = 1;
}
message ErrorCountMetricSet {
  string name = 1;
  FreshnessInfo freshness_info = 2;
}
message QueryErrorCountMetricSetRequest {
  string name = 1;
  TimelineSpec timeline_spec = 2;
  repeated string dimensions = 3;
  repeated string metrics = 4;
  int32 page_size = 5;
  string page_token = 6;
  string filter = 7;
}
message QueryErrorCountMetricSetResponse {
  repeated MetricsRow rows = 1;
  string next_page_token = 2;
}
message IssueAnnotation {
  string category = 1;
  string title = 2;
  string body = 3;
}
enum ErrorType {
  ERROR_TYPE_UNSPECIFIED = 0;
  APPLICATION_NOT_RESPONDING = 1;
  CRASH = 2;
  NON_FATAL = 3;
}
