load("//tools/base/bazel:proto.bzl", "kotlin_proto_library")

package(default_visibility = ["//visibility:public"])

kotlin_proto_library(
    name = "play_findings_proto",
    srcs = glob(["**/*.proto"]),
    visibility = ["//visibility:public"],
)
