syntax = "proto3";

package google.play.androidpublisher.v3;

import "drm_app_compat_finding_data.proto";

option java_package = "com.google.play.androidpublisher.v3";
option java_multiple_files = true;
option java_outer_classname = "FindingDataProto";

// Data associated with a finding that can be used to understand and process
// the finding programmatically.
//
// This is populated on a `Finding` (see finding.proto) only for specific
// finding types that carry structured diagnostic payload.
message FindingData {

  // The specific type-dependent data payload containing structural details of
  // the finding.
  oneof data_type {
    // Data for DRM App Compatibility findings
    // [Finding.Type.DRM_APP_COMPAT][google.play.androidpublisher.v3.Finding.Type.DRM_APP_COMPAT]).
    //
    DrmAppCompatFindingData drm_app_compat = 1;
  }
}
