load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.plugin.descriptor",
    iml_files = ["intellij.android.plugin.descriptor.iml"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    runtime_deps = [
        "@intellij//:com.intellij.properties",
        "@intellij//:com.intellij.modules.json",
        "@intellij//:Git4Idea",
        "@intellij//:org.jetbrains.plugins.gradle",
        "@intellij//:org.intellij.groovy",
        "@intellij//:com.intellij.groovy.scripting",
        "@intellij//:intellij.java.aetherDependencyResolver.plugin",
        "@intellij//:intellij.libraries.misc.plugin",
        "@intellij//:intellij.structuralSearch.plugin",
        "@intellij//:intellij.structureView.plugin",
        "@intellij//:intellij.testRunner.plugin",
        "@intellij//:intellij.todo.plugin",
    ],
)
