buildscript {
  dependencies {
    classpath 'com.android.tools.build:gradle:9.0.0'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10"
  }
}

apply plugin: 'com.android.application'

android {
  compileSdk 33
  defaultConfig {
    namespace "com.example.minapp"
    minSdk 29
    targetSdk 33
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  lintOptions {
    checkReleaseBuilds false
  }
  kotlin {
    compilerOptions {
      jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
  }
}
