load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("//tools/adt/idea/studio:studio.bzl", "studio_data")

# Precompiled Android CLI launchers pulled at build time using http_file.
#
# Under Bzlmod, external files have dynamic repository names in their short_paths.
# To make prefix matching in `studio_data.mappings` stable, we copy the files
# into this package using `copy_file`.
#
# This also allows us to ensure the platform-specific binaries appear under
# `bazel-bin`, making them available to Android Studio when run from sources.

copy_file(
    name = "android_cli_linux_local",
    src = "@android_cli_linux//file",
    out = "linux/android",
    is_executable = True,
)

copy_file(
    name = "android_cli_mac_local",
    src = "@android_cli_mac//file",
    out = "mac/android",
    is_executable = True,
)

copy_file(
    name = "android_cli_mac_arm_local",
    src = "@android_cli_mac_arm//file",
    out = "mac_arm/android",
    is_executable = True,
)

copy_file(
    name = "android_cli_win_local",
    src = "@android_cli_win//file",
    out = "win/android.exe",
    is_executable = True,
)

filegroup(
    name = "android_cli_launchers",
    srcs = [
        ":android_cli_linux_local",
        ":android_cli_mac_arm_local",
        ":android_cli_mac_local",
        ":android_cli_win_local",
    ],
    visibility = ["//tools/adt/idea/android:__pkg__"],
)

studio_data(
    name = "android-cli-launcher-bundle",
    files_linux = [":android_cli_linux_local"],
    files_mac = [":android_cli_mac_local"],
    files_mac_arm = [":android_cli_mac_arm_local"],
    files_win = [":android_cli_win_local"],
    mappings = {
        "tools/adt/idea/android/prebuilts/android-cli/linux/": "android-cli/bin/",
        "tools/adt/idea/android/prebuilts/android-cli/mac/": "android-cli/bin/",
        "tools/adt/idea/android/prebuilts/android-cli/mac_arm/": "android-cli/bin/",
        "tools/adt/idea/android/prebuilts/android-cli/win/": "android-cli/bin/",
    },
    visibility = ["//visibility:public"],
)
